<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/microsoft/vscode/master/extensions/json/syntaxes/json.tmLanguage.schema.json</string>
	<key>fileTypes</key>
	<array>
		<string>sg</string>
	</array>
	<key>name</key>
	<string>Surge</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#compareExpression</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#asyncBlock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#forLoop</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functionDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#contractDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enumDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typeDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tagDefinition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#externBlock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#importStatement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#primitiveTypes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#booleanLiterals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typeConstructors</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typeAnnotations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functionCall</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>asyncBlock</key>
		<dict>
			<key>begin</key>
			<string>\b(async)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.async.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>@([A-Za-z_][A-Za-z0-9_]*)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.attribute.surge</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.annotation.end.surge</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.attribute.arguments.surge</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#booleanLiterals</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>@deprecated\b</string>
					<key>name</key>
					<string>storage.type.attribute.deprecated.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@(allow_to|entrypoint|intrinsic|overload|override|pure|copy)\b</string>
					<key>name</key>
					<string>storage.type.attribute.contract.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@(backend|packed|align|raii|arena|weak|shared)\b</string>
					<key>name</key>
					<string>storage.type.attribute.backend.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@(readonly|hidden|noinherit|sealed)\b</string>
					<key>name</key>
					<string>storage.type.attribute.visibility.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@(guarded_by|requires_lock|acquires_lock|releases_lock|waits_on|send|nosend|nonblocking|failfast|atomic)\b</string>
					<key>name</key>
					<string>storage.type.attribute.concurrency.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@drop\b</string>
					<key>name</key>
					<string>storage.type.attribute.statement.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>@[A-Za-z_][A-Za-z0-9_]*</string>
					<key>name</key>
					<string>storage.type.attribute.surge</string>
				</dict>
			</array>
		</dict>
		<key>booleanLiterals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.boolean.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bnothing\b</string>
					<key>name</key>
					<string>constant.language.nothing.surge</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*///.*$</string>
					<key>name</key>
					<string>comment.line.documentation.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.double-slash.surge</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.surge</string>
				</dict>
			</array>
		</dict>
		<key>compareExpression</key>
		<dict>
			<key>begin</key>
			<string>\b(compare)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.compare.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleanLiterals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#patterns</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
			</array>
		</dict>
		<key>contractDefinition</key>
		<dict>
			<key>begin</key>
			<string>\b(contract)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.surge</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s*[\{;])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(let|const)\b</string>
					<key>name</key>
					<string>keyword.other.variable.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bsignal\b</string>
					<key>name</key>
					<string>keyword.other.signal.surge</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.directive.prefix.surge</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.directive.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(///)\s*([A-Za-z_][A-Za-z0-9_]*)\s*:\s*$</string>
					<key>name</key>
					<string>meta.directive.header.surge</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(///)\s*([A-Za-z_][A-Za-z0-9_]*)(\.|::)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.directive.prefix.surge</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.directive.surge</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.directive.surge</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.surge.directive</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.directive.body.surge</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#strings</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#booleanLiterals</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#attributes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#functionCall</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#primitiveTypes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#operators</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#punctuation</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>enumDefinition</key>
		<dict>
			<key>begin</key>
			<string>\b(enum)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.surge</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s*[\{=])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
			</array>
		</dict>
		<key>externBlock</key>
		<dict>
			<key>begin</key>
			<string>\b(extern)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.extern.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\{)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeAnnotations</string>
				</dict>
			</array>
		</dict>
		<key>forLoop</key>
		<dict>
			<key>begin</key>
			<string>\b(for)\b\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parameters.end.surge</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitiveTypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleanLiterals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#declarations</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#punctuation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_][A-Za-z0-9_]*\b(?=\s*:)</string>
					<key>name</key>
					<string>variable.other.parameter.surge</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeAnnotations</string>
				</dict>
			</array>
		</dict>
		<key>functionCall</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([A-Z][A-Za-z0-9_]*)(?=\s*(?:::&lt;[^&gt;]+&gt;)?\s*\()</string>
					<key>name</key>
					<string>entity.name.tag.constructor.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([a-z_][A-Za-z0-9_]*)(?=\s*(?:::&lt;[^&gt;]+&gt;)?\s*\()</string>
					<key>name</key>
					<string>entity.name.function.call.surge</string>
				</dict>
			</array>
		</dict>
		<key>functionDefinition</key>
		<dict>
			<key>begin</key>
			<string>\b(fn)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.function.surge</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\{|;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functionParameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeAnnotations</string>
				</dict>
			</array>
		</dict>
		<key>functionParameters</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parameters.begin.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parameters.end.surge</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#primitiveTypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleanLiterals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_][A-Za-z0-9_]*\b(?=\s*:)</string>
					<key>name</key>
					<string>variable.other.parameter.surge</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typeAnnotations</string>
				</dict>
			</array>
		</dict>
		<key>generics</key>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.generic.begin.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.generic.end.surge</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#primitiveTypes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bconst\b</string>
					<key>name</key>
					<string>keyword.other.declaration.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_][A-Za-z0-9_]*\b</string>
					<key>name</key>
					<string>variable.other.parameter.surge</string>
				</dict>
			</array>
		</dict>
		<key>importStatement</key>
		<dict>
			<key>begin</key>
			<string>\b(import)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.surge</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.scope.surge</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.wildcard.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(::)\s*(\*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.scope.surge</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.import.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(::)([A-Za-z_][A-Za-z0-9_]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.as.surge</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.alias.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(as)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.begin.surge</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.block.end.surge</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.import.surge</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([A-Za-z_][A-Za-z0-9_]*)</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.comma.surge</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.namespace.surge</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.namespace.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.|\.\.|[A-Za-z_][A-Za-z0-9_]*)(/)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.namespace.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.|\.\.|[A-Za-z_][A-Za-z0-9_]*)</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|while|for|in|return|break|continue|finally)\b</string>
					<key>name</key>
					<string>keyword.control.flow.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bcompare\b</string>
					<key>name</key>
					<string>keyword.other.compare.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bselect\b</string>
					<key>name</key>
					<string>keyword.other.select.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\brace\b</string>
					<key>name</key>
					<string>keyword.other.race.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bparallel\b</string>
					<key>name</key>
					<string>keyword.other.parallel.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bmap\b</string>
					<key>name</key>
					<string>keyword.other.map.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\breduce\b</string>
					<key>name</key>
					<string>keyword.other.reduce.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bwith\b</string>
					<key>name</key>
					<string>keyword.other.with.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\basync\b</string>
					<key>name</key>
					<string>keyword.other.async.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(task|spawn|signal)\b</string>
					<key>name</key>
					<string>keyword.other.concurrency.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bimport\b</string>
					<key>name</key>
					<string>keyword.other.import.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bas\b</string>
					<key>name</key>
					<string>keyword.other.as.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(fn|type|contract|tag|enum|extern|macro|pragma|field)\b</string>
					<key>name</key>
					<string>keyword.other.declaration.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bown\b</string>
					<key>name</key>
					<string>keyword.other.ownership.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(pub|mut)\b</string>
					<key>name</key>
					<string>storage.modifier.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bdefault\b</string>
					<key>name</key>
					<string>keyword.other.default.surge</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?:\b[0-9](?:_?[0-9])*\.(?:[0-9](?:_?[0-9])*)(?:[eE][+-]?[0-9](?:_?[0-9])*)?|\b[0-9](?:_?[0-9])*[eE][+-]?[0-9](?:_?[0-9])*|(?&lt;![\w\.])\.[0-9](?:_?[0-9])*(?:[eE][+-]?[0-9](?:_?[0-9])*)?)(?:[A-Za-z][A-Za-z0-9_]*)?\b</string>
					<key>name</key>
					<string>constant.numeric.float.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?:0b[01_]+|0o[0-7_]+|0x[0-9a-fA-F_]+|[0-9](?:_?[0-9])*)(?:[A-Za-z][A-Za-z0-9_]*)?\b</string>
					<key>name</key>
					<string>constant.numeric.int.surge</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>:=</string>
					<key>name</key>
					<string>keyword.operator.assignment.reactive.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+=|-=|\*=|/=|%=|&amp;=|\|=|\^=|&lt;&lt;=|&gt;&gt;=</string>
					<key>name</key>
					<string>keyword.operator.assignment.compound.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bto\b</string>
					<key>name</key>
					<string>keyword.operator.cast.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bis\b</string>
					<key>name</key>
					<string>keyword.operator.type-check.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bheir\b</string>
					<key>name</key>
					<string>keyword.operator.heir.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?\?</string>
					<key>name</key>
					<string>keyword.operator.null-coalescing.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?</string>
					<key>name</key>
					<string>keyword.operator.question.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.\.</string>
					<key>name</key>
					<string>keyword.operator.variadic.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.=?</string>
					<key>name</key>
					<string>keyword.operator.range.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;&lt;|&gt;&gt;</string>
					<key>name</key>
					<string>keyword.operator.shift.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|\||&amp;&amp;|!(?!=)</string>
					<key>name</key>
					<string>keyword.operator.logical.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?:\|(?![|=])|\^(?!=))</string>
					<key>name</key>
					<string>keyword.operator.bitwise.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;(?![&amp;=])</string>
					<key>name</key>
					<string>keyword.operator.reference.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+|-(?!&gt;)|\*(?![*/])|/(?![/*])|%</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
					<key>name</key>
					<string>keyword.operator.comparison.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;|=&gt;|=</string>
					<key>name</key>
					<string>keyword.operator.surge</string>
				</dict>
			</array>
		</dict>
		<key>patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bfinally\b</string>
					<key>name</key>
					<string>keyword.control.pattern.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=&gt;</string>
					<key>name</key>
					<string>keyword.operator.pattern-match.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([A-Z][A-Za-z0-9_]*)(?=\s*\()</string>
					<key>name</key>
					<string>entity.name.tag.constructor.surge</string>
				</dict>
			</array>
		</dict>
		<key>primitiveTypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bchannel\b</string>
					<key>name</key>
					<string>support.type.channel.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(int|uint|float|bool|string|unit|int8|int16|int32|int64|uint8|uint16|uint32|uint64|float16|float32|float64)\b</string>
					<key>name</key>
					<string>storage.type.primitive.surge</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{</string>
					<key>name</key>
					<string>punctuation.section.block.begin.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\}</string>
					<key>name</key>
					<string>punctuation.section.block.end.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[</string>
					<key>name</key>
					<string>punctuation.section.brackets.begin.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\]</string>
					<key>name</key>
					<string>punctuation.section.brackets.end.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(</string>
					<key>name</key>
					<string>punctuation.section.parens.begin.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\)</string>
					<key>name</key>
					<string>punctuation.section.parens.end.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.comma.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>;</string>
					<key>name</key>
					<string>punctuation.separator.semicolon.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>::</string>
					<key>name</key>
					<string>punctuation.separator.scope.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:(?![:=])</string>
					<key>name</key>
					<string>punctuation.separator.colon.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.(?!\.)</string>
					<key>name</key>
					<string>punctuation.accessor.dot.surge</string>
				</dict>
			</array>
		</dict>
		<key>stringEscapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(n|r|t|"|\\)</string>
					<key>name</key>
					<string>constant.character.escape.surge</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\u\{[0-9a-fA-F]+\}</string>
					<key>name</key>
					<string>constant.character.escape.surge</string>
				</dict>
			</array>
		</dict>
		<key>stringInterpolations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{\{|\}\}</string>
					<key>name</key>
					<string>constant.character.escape.surge</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{(?!\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.interpolation.begin.surge</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.surge</string>
					<key>end</key>
					<string>\}(?!\})</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.interpolation.end.surge</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.interpolation.surge</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(f)(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.string.prefix.surge</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.surge</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.surge</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.interpolated.surge</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringEscapes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#stringInterpolations</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.surge</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.surge</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.surge</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#stringEscapes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tagDefinition</key>
		<dict>
			<key>begin</key>
			<string>\b(tag)\s+([A-Z][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.surge</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.tag.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functionParameters</string>
				</dict>
			</array>
		</dict>
		<key>typeAnnotations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.type.surge</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.surge</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type.reference.surge</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:)(\s*)(own\s+)?(&amp;mut\s*|&amp;\s*|\*\s*)?([A-Za-z_][A-Za-z0-9_]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.type.result.surge</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.surge</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type.reference.surge</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.surge</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(-&gt;)(\s*)(own\s+)?(&amp;mut\s*|&amp;\s*|\*\s*)?([A-Za-z_][A-Za-z0-9_]*)</string>
				</dict>
			</array>
		</dict>
		<key>typeConstructors</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\btype\s)(?&lt;!\btag\s)(?&lt;!\bcontract\s)(?&lt;!\benum\s)\b[A-Z][A-Za-z0-9_]*\b(?=\s*\{)</string>
					<key>name</key>
					<string>entity.name.type.surge</string>
				</dict>
			</array>
		</dict>
		<key>typeDefinition</key>
		<dict>
			<key>begin</key>
			<string>\b(type)\s+([A-Za-z_][A-Za-z0-9_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.type.surge</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.surge</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\s*[\{=])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#generics</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.surge</string>
</dict>
</plist>
